version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgres://ecommerce_user:postgres@db:5432/ecommerce_development
    ports:
      - "9292:9292"
    depends_on:
      - db

volumes:
  db_data:
