source "https://rubygems.org"
ruby '3.2.2'

gem 'activerecord'
gem 'pg'
gem 'puma', '~> 6.0'
gem 'sinatra'
gem 'email_address'
gem 'dry-transaction'
gem 'guard'
gem 'guard-puma'
gem 'jwt'
gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'enumerize'


