require 'pg'
require 'yaml'

db_config = YAML.load_file('config/database.yml')
conn = PG.connect( db_config['devlopement'] )

# conn.exec("DROP TABLE if exists users cascade;")
conn.exec("DROP TABLE if exists wallets cascade;")

conn.exec("CREATE TABLE IF NOT EXISTS wallets (
  name VARCHAR(50),
  number VARCHAR(50),
  csv VARCHAR(50),
  exprired_at Date,
  user_id INT,
  CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id)
)")

conn.exec("CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50),
  email VARCHAR(100),
  password VARCHAR(100),
  session_token VARCHAR(256)
)")
